### PR TITLE
Fix document Links and Camera Pictures, Use math script for equations

### PR DESCRIPTION
**Pull request by jacobagilbert**
The docs for this project are really great. Just some minor random fixes as a show of appreciation.

I am not 100% sure that gitbook will resolve the TeX equations, ill revert if that causes issues on gitbook but I'm pretty sure this works.

One significant change on the X86 page, I believe what is on there is currently an error and you need to run QOpenHD for **Ground** operation, not Air.

### CODE REVIEW

**Comment by raphaelscholle** [comment]
thanks for the contribution, but it looks like the math-stuff isn't working

**Comment by jacobagilbert** [comment]
Darn! Neither are the camera images :(

They look nice on other markdown readers including github though, unfortunate.

I'll get a fix in, sorry.

**Comment by raphaelscholle** [comment]
no worries, I'm very glad that you help there, the documentation is something that often gets pushed to the "is not that important" area, since there is a lot of stuff that looks more important in the eyes of a developer.

**Comment by jacobagilbert** [comment]
Definitely get it. I hope to contribute more but I can definitely help w/ docs for now.

**Pull request merged**
